### ISSUE TITLE
The Swagger UI is not enabled in the Higress all-in-one

### ISSUE THREAD

**Issue by cr7258** [higress-group/higress-console#583]
- [x] I have searched the [issues](https://github.com/alibaba/higress/issues) of this repository and believe that this is not a duplicate.

### Issue Description

Follow the [guide](https://higress.cn/en/docs/latest/ops/how-tos/enable-swagger/?spm=36971b57.2acddb42.0.0.58683d2bJYWDzQ#all-in-one-image-deployment) and set the `O11Y=on` environment variable to enable Swagger UI in Higress all-in-one, but it didn't work.

<img width="1780" height="530" alt="Image" src="https://github.com/user-attachments/assets/7b8895fb-28d0-4e0b-9939-b0f2385756ff" />

<img width="2506" height="708" alt="Image" src="https://github.com/user-attachments/assets/06b1962a-d8c6-46cd-8bb3-957f43da24f1" />

### Describe what you expected to happen

The Swagger UI is visible.

### How to reproduce it (as minimally and precisely as possible)

Add `-e O11Y=on` in the `https://higress.cn/ai-gateway/install.sh`, and run the script.

<img width="2002" height="1100" alt="Image" src="https://github.com/user-attachments/assets/553045e0-9233-4aa3-b887-d8d2cc6d18cc" />

### Environment:

- Higress version:  higress-registry.cn-hangzhou.cr.aliyuncs.com/higress/all-in-one:latest
- OS : MacOS
- Others:

**Comment by CH3CHO** [comment]
The doc was wrong. And I just fixed it. Please check it out.

https://higress.cn/docs/latest/ops/how-tos/enable-swagger/

**Comment by cr7258** [comment]
I have added two environment variables, but I still can't open the Swagger UI page.
```bash
docker exec -it higress-ai-gateway env |grep SPRINGDOC
SPRINGDOC_API_DOCS_ENABLED=true
SPRINGDOC_SWAGGER_UI_ENABLED=true
```

<img width="1658" height="542" alt="Image" src="https://github.com/user-attachments/assets/cd327a0d-4183-465b-bbbe-8a837534655d" />
